// Profile and project information adapted from your existing portfolio.
export const profile = {
  name: "Jay-r",
  fullName: "Jay-r B. Casano",
  role: "Full-Stack Developer",
  location: "General Trias, Cavite, PH",
  email: "jayrcasano01@gmail.com",
  github: "https://github.com/Jeyarrr",
  linkedin: "https://www.linkedin.com/in/jay-r-casano-b3760a238/",
  intro:
    "Thoughtful interfaces. Reliable systems. I connect frontend, backend, and databases to turn good ideas into software that works for people.",
  about: [
    "Hello! I'm Jay-r Casano, an aspiring Full-Stack Developer and Associate ASP.NET Developer with a passion for building modern, efficient, and user-friendly web applications. I enjoy transforming ideas into functional software and continuously improving my skills through hands-on projects and real-world experience.",
    "I completed my internship as a Junior Software Developer and IT Support, where I gained practical experience in software development, debugging, system maintenance, and technical support. Working in both development and IT support strengthened my problem-solving abilities, attention to detail, and understanding of how technology helps businesses operate efficiently.",
    "My technical skills include ASP.NET, C#, HTML, CSS, JavaScript, Tailwind CSS, Microsoft SQL Server, Git, and .NET. I currently build with the PERN stack (PostgreSQL, Express.js, React, and Node.js), use Supabase in my projects, and deploy with Vercel. I'm continuing to expand my knowledge in full-stack development and modern web technologies while building projects that challenge me to grow as a developer.",
    "Outside of coding, I enjoy learning new technologies, exploring software development best practices, and continuously improving my craft. My goal is to become a skilled Full-Stack Developer who creates reliable, scalable, and meaningful digital solutions.",
    "I believe that every project is an opportunity to learn, improve, and make a positive impact through technology.",
  ],
};

export const projects = [
  {
    id: "techora",
    name: "TechOra",
    type: "Web apps",
    label: "FULL-STACK E-COMMERCE",
    featured: true,
    description:
      "From product discovery to order management. A complete tech storefront connecting a considered shopping experience with the systems behind it.",
    tags: ["React", "Node.js", "Express", "PostgreSQL"],
    color: "techora-blue",
    url: "https://techora-store.vercel.app/",
    github: "https://github.com/Jeyarrr/TechOra",
    image: "",
    summary:
      "A full-stack technology e-commerce platform with customer shopping, order tracking, product reviews, and an admin management dashboard. Built with React and Vite on the frontend, Node.js and Express on the backend, and PostgreSQL for data storage.",
    features: [
      "Customer storefront and product discovery",
      "Order tracking and customer reviews",
      "Admin management dashboard",
    ],
  },
  {
    id: "tastenet",
    name: "TASTENET",
    type: "Web apps",
    label: "FOOD ORDERING & DELIVERY",
    featured: true,
    image: "/projects/tastenet/home.png",
    gallery: [
      {
        src: "/projects/tastenet/home.png",
        label: "Customer home",
        alt: "TasteNet customer homepage with meal search and ordering",
        width: 1897,
        height: 907,
      },
      {
        src: "/projects/tastenet/sign-in.png",
        label: "Sign in",
        alt: "TasteNet customer sign-in screen",
        width: 1907,
        height: 901,
      },
      {
        src: "/projects/tastenet/account-menu.png",
        label: "Account menu",
        alt: "TasteNet customer account menu on the homepage",
        width: 1917,
        height: 906,
      },
      {
        src: "/projects/tastenet/my-orders.png",
        label: "My orders",
        alt: "TasteNet customer active orders and order history",
        width: 1917,
        height: 902,
      },
      {
        src: "/projects/tastenet/item-details.png",
        label: "Item details",
        alt: "TasteNet food item details and add-on options",
        width: 1917,
        height: 900,
      },
      {
        src: "/projects/tastenet/cart.png",
        label: "Cart",
        alt: "TasteNet cart with order total and checkout controls",
        width: 1917,
        height: 901,
      },
      {
        src: "/projects/tastenet/order-confirmed.png",
        label: "Order placed",
        alt: "TasteNet order confirmation after checkout",
        width: 1917,
        height: 902,
      },
      {
        src: "/projects/tastenet/admin-dashboard.png",
        label: "Admin dashboard",
        alt: "TasteNet admin dashboard with sales and activity metrics",
        width: 1915,
        height: 911,
      },
      {
        src: "/projects/tastenet/inventory.png",
        label: "Inventory",
        alt: "TasteNet inventory management with ingredient stock levels",
        width: 1917,
        height: 902,
      },
      {
        src: "/projects/tastenet/recipes.png",
        label: "Recipes",
        alt: "TasteNet recipe manager for menu ingredients",
        width: 1917,
        height: 906,
      },
      {
        src: "/projects/tastenet/menu-management.png",
        label: "Menu management",
        alt: "TasteNet admin menu management with food categories and dishes",
        width: 1917,
        height: 903,
      },
      {
        src: "/projects/tastenet/tickets.png",
        label: "Tickets",
        alt: "TasteNet admin order ticket management",
        width: 1917,
        height: 907,
      },
      {
        src: "/projects/tastenet/transactions.png",
        label: "Transactions",
        alt: "TasteNet transaction management and purchase records",
        width: 1917,
        height: 912,
      },
      {
        src: "/projects/tastenet/rider-dashboard.png",
        label: "Rider dashboard",
        alt: "TasteNet rider dashboard with availability and delivery summary",
        width: 1917,
        height: 902,
      },
      {
        src: "/projects/tastenet/delivery-history.png",
        label: "Delivery history",
        alt: "TasteNet rider completed delivery history",
        width: 1917,
        height: 900,
      },
      {
        src: "/projects/tastenet/rider-profile.png",
        label: "Rider profile",
        alt: "TasteNet rider profile and account settings",
        width: 1917,
        height: 910,
      },
    ],
    description:
      "Connecting a community through food. An ordering and delivery management system built for CABALLEROS.",
    tags: ["ASP.NET", "C#", "SQL Server", "Tailwind CSS"],
    color: "lavender",
    url: "http://tastenet9-001-site1.itempurl.com/LandingPage.aspx",
    summary:
      "A web-based community food ordering and delivery management system built for CABALLEROS using ASP.NET Web Forms, C#, SQL Server, and Tailwind CSS.",
    features: [
      "Customer food ordering",
      "Admin oversight and staff fulfillment",
      "Rider proof-of-delivery modules",
    ],
  },
  {
    id: "jbnav",
    name: "JB Nav Enterprise",
    type: "Websites",
    label: "EVENTS & CATERING WEBSITE",
    description:
      "A welcoming digital presence for a premium party and catering company, from first impressions to event inquiries.",
    tags: ["HTML", "CSS", "JavaScript"],
    color: "sand",
    url: "https://jeyarrr.github.io/JB-Nav-Enterprise/",
    github: "https://github.com/Jeyarrr/JB-Nav-Enterprise",
    image: "/projects/jbnav/home.png",
    gallery: [
      {
        src: "/projects/jbnav/home.png",
        label: "Home",
        alt: "JB Nav Enterprise homepage and event booking call to action",
        width: 1905,
        height: 906,
      },
      {
        src: "/projects/jbnav/about.png",
        label: "About",
        alt: "JB Nav Enterprise introduction and company highlights",
        width: 1910,
        height: 910,
      },
      {
        src: "/projects/jbnav/services.png",
        label: "Services",
        alt: "JB Nav Enterprise catering, event planning, and entertainment services",
        width: 1906,
        height: 906,
      },
      {
        src: "/projects/jbnav/gallery.png",
        label: "Gallery",
        alt: "JB Nav Enterprise gallery of event setups and celebrations",
        width: 1907,
        height: 910,
      },
      {
        src: "/projects/jbnav/booking.png",
        label: "Book now",
        alt: "JB Nav Enterprise event booking request form",
        width: 1907,
        height: 911,
      },
      {
        src: "/projects/jbnav/contact.png",
        label: "Contact",
        alt: "JB Nav Enterprise contact details and message form",
        width: 1905,
        height: 906,
      },
    ],
    summary:
      "A responsive website for JB Nav Enterprise, a premium party and catering company. Designed to showcase services, build client trust, and help prospective customers make event inquiries.",
    features: [
      "Service and event presentation",
      "Responsive layouts",
      "Clear paths to customer inquiries",
    ],
  },
  {
    id: "jbank",
    name: "JBank",
    type: "UI / UX",
    label: "MOBILE BANKING EXPERIENCE",
    description:
      "Everyday banking, thoughtfully designed. A mobile experience focused on clarity, confidence, and ease of use.",
    tags: ["Figma", "UI / UX", "Prototyping"],
    color: "green",
    image: "/projects/jbank-overview.png",
    gallery: [
      {
        src: "/projects/jbank-overview.png",
        label: "Overview",
        alt: "JBank welcome, sign-up, home, and investment screen designs",
        width: 1294,
        height: 714,
      },
      {
        src: "/projects/jbank-transfers.png",
        label: "Banking flows",
        alt: "JBank transfer, pay and e-wallet, and profile screen designs",
        width: 991,
        height: 708,
      },
    ],
    url: "https://www.figma.com/proto/qfXGW9uZCLZubzEPDtqDV8?node-id=0-1&t=WGB5T80IAi4NUXnd-6",
    summary:
      "A mobile banking application design created in Figma, exploring a secure, intuitive, and user-focused experience. Includes a design system and prototypes for core banking functions.",
    features: [
      "Mobile banking interface design",
      "Reusable design system",
      "Interactive banking prototypes",
    ],
  },
];
